["package:src:webui:fix:prettier"]
hide = true
run = "npx prettier --write --list-different src/webui"

["package:src:webui:fix:eslint"]
hide = true
run = "npx eslint src/webui --fix"

["package:src:webui:fix"]
description = "Fix src/webui module"
depends = ["package:src:webui:fix:*"]
run = "true"

["package:src:webui:lint:tsc"]
hide = true
run = "cd src/webui && npx tsc"

["package:src:webui:lint:prettier"]
hide = true
run = "npx prettier --check src/webui"

["package:src:webui:lint:eslint"]
hide = true
run = "npx eslint src/webui"

["package:src:webui:lint"]
description = "Check src/webui module"
depends = ["package:src:webui:lint:*"]
run = "true"
