["package:src:webui:prepare"]
hide = true
run = "true"

["package:src:webui:fix:prettier"]
hide = true
sources = ["src/webui/**/*.{ts,tsx,js,jsx,json,md}"]
outputs = { auto = true }
run = "npx prettier --write --list-different src/webui"

["package:src:webui:fix:eslint"]
hide = true
sources = ["src/webui/**/*.{ts,tsx,js,jsx}"]
outputs = { auto = true }
run = "npx eslint src/webui --fix"

["package:src:webui:fix"]
description = "Fix src/webui module"
depends = ["package:src:webui:fix:*"]
run = "true"

["package:src:webui:lint:hadolint"]
hide = true
sources = ["src/webui/Dockerfile"]
outputs = { auto = true }
run = '''
#!/usr/bin/env bash
set -e -o pipefail
docker run --rm -i \
  -v "$(pwd)/tasks/_resources/check/lint/hadolint":/hadolint \
  -v "$(pwd)/src/webui/Dockerfile:/Dockerfile" \
  hadolint/hadolint:latest-debian \
  hadolint \
  --config=/hadolint \
  /Dockerfile
'''

["package:src:webui:lint:toml"]
hide = true
sources = ["src/webui/package.mise.toml"]
outputs = { auto = true }
run = "npx eslint src/webui/package.mise.toml"

["package:src:webui:lint:tsc"]
hide = true
sources = ["src/webui/**/*.{ts,tsx}"]
outputs = { auto = true }
run = "cd src/webui && npx tsc"

["package:src:webui:lint:prettier"]
hide = true
sources = ["src/webui/**/*.{ts,tsx,js,jsx,json,md}"]
outputs = { auto = true }
run = "npx prettier --check src/webui"

["package:src:webui:lint:eslint"]
hide = true
sources = ["src/webui/**/*.{ts,tsx,js,jsx}"]
outputs = { auto = true }
run = "npx eslint src/webui"

["package:src:webui:lint:mdl-readme"]
hide = true
sources = ["src/webui/README.md"]
outputs = { auto = true }
run = "mdl --config=\"./tasks/_resources/check/lint/mdl-readme\" src/webui/README.md"

["package:src:webui:lint"]
description = "Check src/webui module"
depends = ["package:src:webui:lint:*"]
run = "true"

["package:src:webui:audit:pnpm-audit"]
hide = true
run = "cd src/webui && pnpm audit"

["package:src:webui:audit"]
description = "Audit src/webui module"
depends = ["package:src:webui:audit:*"]
run = "true"

["package:src:webui:libyear:pnpm-libyear"]
hide = true
run = "cd src/webui && npx libyear"

["package:src:webui:libyear"]
description = "Check src/webui libyear"
depends = ["package:src:webui:libyear:*"]
run = "true"
