[tools]
cocoapods = "latest"
gcloud = "latest"
"github:cli/cli" = "latest"
jq = "latest"
node = "22.14.0"
poetry = "latest"
python = "3.13.0"
ruby = "2.7"
rust = "latest"

[env]
_.python.venv = { path = ".build-cache/venv", create = true }

[task_config]
includes = [
    "tasks",
    "root.mise.toml",
    "src/core/mise.toml",
    "src/cli/mise.toml",
    "src/webapi/mise.toml",
    "src/docs/mise.toml",
    "src/webui/mise.toml",
    "src/desktop/mise.toml",
    "src/mobile/mise.toml",
    "itests/mise.toml",
]
