previews:
  generation: automatic
  expireAfterDays: 1

services:
- type: web
  name: jupiter-webui
  runtime: docker
  dockerfilePath: ./src/webui/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  domains:
    - app.get-thriving.com
  previews:
    generation: automatic
    plan: starter
  envVars:
    - key: UNIVERSE
      value: thrive
    - key: ENV
      value: production
      previewValue: staging
    - key: INSTANCE
      value: Main
      previewValue: TO-FILL
    - key: WEBAPI_SERVER_HOST
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: host
    - key: WEBAPI_SERVER_PORT
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: port
    - key: WEBAPI_URL
      fromService:
        name: jupiter-webapi-srv
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: WEBUI_URL
      value: https://app.get-thriving.com
    - key: API_URL
      value: https://api.get-thriving.com
    - key: MCP_URL
      value: https://mcp.get-thriving.com
    - key: DOCS_URL
      value: https://docs.get-thriving.com
    - key: SESSION_COOKIE_SECURE
      value: true
- type: web
  name: jupiter-webapi-srv
  runtime: docker
  dockerfilePath: ./src/webapi/srv/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  domains:
    - api.infra.get-thriving.com
  previews:
    generation: automatic
    plan: starter
  disk:
      name: jupiter-data
      mountPath: /data
      sizeGB: 5
  envVars:
    - key: UNIVERSE
      value: thrive
    - key: ENV
      value: production
      previewValue: staging
    - key: INSTANCE
      value: Main
      previewValue: TO-FILL
    - key: SQLITE_DB_URL
      value: sqlite+aiosqlite:////data/jupiter.sqlite
    - key: POSTGRES_DB_URL
      fromDatabase:
        name: jupiter-webapi-srv-db
        property: connectionString
    - key: ALEMBIC_INI_PATH
      value: /jupiter/src/core/migrations/alembic.postgres.ini
    - key: ALEMBIC_MIGRATIONS_PATH
      value: /jupiter/src/core/migrations/postgres
    - key: WEBAPI_STORAGE_ENGINE
      value: postgres
    - key: WEBAPI_TELEMETRY
      value: sentry
      previewValue: sentry
    - key: WEBAPI_SEARCH
      value: algolia
    - key: WEBAPI_CRM
      value: wix
      previewValue: noop
- type: web
  name: jupiter-api
  domains:
    - api.get-thriving.com
  runtime: docker
  dockerfilePath: ./src/api/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  previews:
    generation: automatic
    plan: starter
  envVars:
    - key: UNIVERSE
      value: thrive
    - key: ENV
      value: production
      previewValue: staging
    - key: INSTANCE
      value: Main
      previewValue: TO-FILL
    - key: WEBAPI_SERVER_HOST
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: host
    - key: WEBAPI_SERVER_PORT
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: port
- type: web
  name: jupiter-mcp
  runtime: docker
  dockerfilePath: ./src/mcp/Dockerfile
  domains:
    - mcp.get-thriving.com
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  previews:
    generation: automatic
    plan: starter
  envVars:
    - key: UNIVERSE
      value: thrive
    - key: ENV
      value: production
      previewValue: staging
    - key: INSTANCE
      value: Main
      previewValue: TO-FILL
    - key: WEBAPI_SERVER_HOST
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: host
    - key: WEBAPI_SERVER_PORT
      fromService:
        name: jupiter-webapi-srv
        type: web
        property: port
- type: web
  name: jupiter-docs
  runtime: static
  buildCommand: ./tasks/build/docs.sh
  staticPublishPath: .build-cache/docs
  domains:
    - docs.get-thriving.com
  previews:
    generation: automatic
  envVars:
    - key: UNIVERSE
      value: thrive
    - key: ENV
      value: production
      previewValue: staging
    - key: INSTANCE
      value: Main
      previewValue: TO-FILL
    - key: UV_VERSION
      value: 0.9.11
    - key: NODE_VERSION
      value: 22.14.0
    - key: PYTHON_VERSION
      value: 3.13.0
    - key: API_URL
      fromService:
        name: jupiter-api
        type: web
        envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: jupiter-webapi-srv-db
    region: frankfurt
    postgresMajorVersion: "18"
    plan: basic-4gb
    previewPlan: basic-1gb
    databaseName: jupiter
    user: jupiter
