["root:audit:pip-audit"]
hide = true
run = '''
#!/usr/bin/env bash
set -ex
poetry run pip-audit -r <(poetry export -f requirements.txt --all-groups --without-hashes)
'''

["root:audit:npm-audit"]
hide = true
run = "npm audit --audit-level=info"

["root:audit"]
description = "Audit root dependencies"
depends = ["root:audit:*"]
run = "true"

["root:libyear:libyear-toml"]
hide = true
run = "libyear toml pyproject.toml"

["root:libyear:npm-libyear"]
hide = true
run = "npx libyear"

["root:libyear"]
description = "Check root libyear"
depends = ["root:libyear:*"]
run = "true"

["root:lint:yamllint-workflows"]
hide = true
run = "poetry run yamllint --config-file=./scripts/check/lint/yamllint .github/"

["root:lint:mdl-docs"]
hide = true
run = "mdl --config=\"./scripts/check/lint/mdl-docs\" docs"

["root:lint:mdl-readme"]
hide = true
run = "mdl --config=\"./scripts/check/lint/mdl-readme\" README.md"

["root:lint"]
description = "Check root lint"
depends = ["root:lint:*"]
run = "true"
