["package:src:cli:fix:autoflake"]
hide = true
run = "poetry run autoflake --config=scripts/check/lint/autoflake src/cli"

["package:src:cli:fix:black"]
hide = true
run = "poetry run black src/cli"

["package:src:cli:fix:ruff"]
hide = true
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/cli --fix"

["package:src:cli:fix"]
description = "Fix src/cli module"
depends = ["package:src:cli:fix:*"]
run = "true"

["package:src:cli:lint:mypy"]
env.MYPYPATH = "../core"
hide = true
run = "cd src/cli && poetry run mypy --config=../../scripts/check/lint/mypy --package jupiter.cli --package tests --explicit-package-bases --show-absolute-path"

["package:src:cli:lint:ruff"]
env.MYPYPATH = "../core"
hide = true
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/cli"

["package:src:cli:lint"]
description = "Check src/cli module"
depends = ["package:src:cli:lint:*"]
run = "true"