["package:gen:py:webapi-client:lint:toml"]
hide = true
sources = ["gen/py/webapi-client/package.mise.toml"]
outputs = { auto = true }
run = "npx eslint gen/py/webapi-client/package.mise.toml"

["package:gen:py:webapi-client:lint"]
hide = true
depends = ["package:gen:py:webapi-client:lint:*"]
run = "true"

["package:gen:py:webapi-client:prepare"]
hide = true
run = "true"
