[project]
name = "jupiter-mcp"
version = "0.1.0"
description = "An MCP server for Thrive."
authors = [{ name = "Mike Bestcat", email = "mike@get-thriving.com" }]
requires-python = ">=3.13,<4"
readme = "README.md"
license = "MIT"
dependencies = [
    "jupiter-framework",
    "jupiter-core",
    "jupiter-webapi-client",
    "fastapi>=0.142.2,<0.143",
    "uvicorn>=0.54.0,<0.55",
    "pydantic>=2.10.6,<3",
    "gunicorn>=26.2.0,<27",
    "python-dotenv>=1.0.1,<2",
    "greenlet>=3.1.1,<4",
    "mcp>=2.3.0,<3",
]

[project.urls]
Homepage = "https://get-thriving.com"
Repository = "https://github.com/get-thriving/thrive"
Documentation = "https://docs.get-thriving.com"

[dependency-groups]
dev = []

[tool.uv]
package = false

[tool.uv.sources]
jupiter-framework = { workspace = true }
jupiter-core = { workspace = true }
jupiter-webapi-client = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
