["package:src:mobile:fix:prettier"]
hide = true
run = "npx prettier --write --list-different src/mobile"

["package:src:mobile:fix"]
description = "Fix src/mobile module"
depends = ["package:src:mobile:fix:*"]
run = "true"

["package:src:mobile:lint:prettier"]
hide = true
run = "npx prettier --check src/mobile"

["package:src:mobile:lint"]
description = "Check src/mobile module"
depends = ["package:src:mobile:lint:*"]
run = "true"

["package:src:mobile:audit:npm-audit"]
hide = true
run = "cd src/mobile && npm audit --audit-level=high"

["package:src:mobile:audit"]
description = "Audit src/mobile module"
depends = ["package:src:mobile:audit:*"]
run = "true"
