["package:src:desktop:fix:prettier"]
hide = true
run = "npx prettier --write --list-different src/desktop"

["package:src:desktop:fix"]
description = "Fix src/desktop module"
depends = ["package:src:desktop:fix:*"]
run = "true"

["package:src:desktop:lint:prettier"]
hide = true
run = "npx prettier --check src/desktop"

["package:src:desktop:lint:mdl-readme"]
hide = true
run = "mdl --config=\"./scripts/check/lint/mdl-readme\" src/desktop/README.md"

["package:src:desktop:lint"]
description = "Check src/desktop module"
depends = ["package:src:desktop:lint:*"]
run = "true"

["package:src:desktop:audit:npm-audit"]
hide = true
run = "cd src/desktop && npm audit --audit-level=high"

["package:src:desktop:audit"]
description = "Audit src/desktop module"
depends = ["package:src:desktop:audit:*"]
run = "true"

["package:src:desktop:libyear:npm-libyear"]
hide = true
run = "cd src/desktop && npx libyear"

["package:src:desktop:libyear"]
description = "Check src/desktop libyear"
depends = ["package:src:desktop:libyear:*"]
run = "true"
