["package:src:core:fix:autoflake"]
hide = true
run = "poetry run autoflake --config=scripts/check/lint/autoflake src/core"

["package:src:core:fix:black"]
hide = true
run = "poetry run black src/core"

["package:src:core:fix:ruff"]
hide = true
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/core --fix"

["package:src:core:fix"]
description = "Fix src/core module"
depends = ["package:src:core:fix:*"]
run = "true"

["package:src:core:lint:mypy"]
hide = true
run = "cd src/core && poetry run mypy --config=../../scripts/check/lint/mypy --package jupiter.core --package tests --explicit-package-bases --show-absolute-path"

["package:src:core:lint:ruff"]
hide = true
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/core"

["package:src:core:lint:mdl-readme"]
hide = true
run = "mdl --config=\"./scripts/check/lint/mdl-readme\" src/core/README.md"

["package:src:core:lint"]
description = "Check src/core module"
depends = ["package:src:core:lint:*"]
run = "true"

["package:src:core:audit:pip-audit"]
hide = true
run = '''
#!/usr/bin/env bash
set -ex
cd src/core
poetry run pip-audit -r <(poetry export -f requirements.txt --all-groups --without-hashes)
'''

["package:src:core:audit"]
description = "Audit src/core module"
depends = ["package:src:core:audit:*"]
run = "true"

["package:src:core:libyear:libyear-toml"]
hide = true
run = "libyear toml src/core/pyproject.toml"

["package:src:core:libyear"]
description = "Check src/core libyear"
depends = ["package:src:core:libyear:*"]
run = "true"