["package:gen:ts:webapi-client:prepare"]
hide = true
run = "cd gen/ts/webapi-client && npx tsc"

["package:gen:ts:webapi-client:install"]
hide = true
run = "cd gen/ts/webapi-client && npm install --no-save"
