["package:gen:ts:webapi-client:lint:toml"]
hide = true
sources = ["gen/ts/webapi-client/package.mise.toml"]
outputs = { auto = true }
run = "npx eslint gen/ts/webapi-client/package.mise.toml"

["package:gen:ts:webapi-client:lint"]
hide = true
depends = ["package:gen:ts:webapi-client:lint:*"]
run = "true"

["package:gen:ts:webapi-client:prepare"]
hide = true
run = "cd gen/ts/webapi-client && npx tsc"

["package:gen:ts:webapi-client:install"]
hide = true
run = "true"
