["package:src:webapi:install"]
hide = true
sources = ["src/webapi/pyproject.toml"]
outputs = { auto = true }
run = "cd src/webapi && poetry install --no-interaction --no-ansi"

["package:src:webapi:fix:autoflake"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run autoflake --config=scripts/check/lint/autoflake src/webapi"

["package:src:webapi:fix:black"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run black src/webapi"

["package:src:webapi:fix:ruff"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/webapi --fix"

["package:src:webapi:fix"]
description = "Fix src/webapi module"
depends = ["package:src:webapi:fix:*"]
run = "true"

["package:src:webapi:lint:hadolint"]
hide = true
sources = ["src/webapi/Dockerfile"]
outputs = { auto = true }
run = '''
#!/usr/bin/env bash
set -ex
docker run --rm -i \
  -v "$(pwd)/scripts/check/lint/hadolint":/hadolint \
  -v "$(pwd)/src/webapi/Dockerfile:/Dockerfile" \
  hadolint/hadolint:latest-debian \
  hadolint \
  --config=/hadolint \
  /Dockerfile
'''

["package:src:webapi:lint:mypy"]
env.MYPYPATH = "../core"
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "cd src/webapi && poetry run mypy --config=../../scripts/check/lint/mypy --package jupiter.webapi --package tests --explicit-package-bases --show-absolute-path"

["package:src:webapi:lint:ruff"]
env.MYPYPATH = "../core"
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run ruff check --cache-dir=.build-cache/ruff --config=./scripts/check/lint/ruff.toml src/webapi"

["package:src:webapi:lint:mdl-readme"]
hide = true
sources = ["src/webapi/README.md"]
outputs = { auto = true }
run = "mdl --config=\"./scripts/check/lint/mdl-readme\" src/webapi/README.md"

["package:src:webapi:lint:pyflakes"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run pyflakes src/webapi"

["package:src:webapi:lint:bandit"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run bandit --configfile=./scripts/check/lint/bandit --ini=./scripts/check/lint/bandit.src.ini -r src/webapi"

["package:src:webapi:lint:pydocstyle"]
hide = true
sources = ["src/webapi/**/*.py"]
outputs = { auto = true }
run = "poetry run pydocstyle --config=./scripts/check/lint/pydocstyle src/webapi"

["package:src:webapi:lint"]
description = "Check src/webapi module"
depends = ["package:src:webapi:lint:*"]
run = "true"

["package:src:webapi:audit:pip-audit"]
hide = true
run = '''
#!/usr/bin/env bash
set -ex
cd src/webapi
poetry run pip-audit -r <(poetry export -f requirements.txt --all-groups --without-hashes)
'''

["package:src:webapi:audit"]
description = "Audit src/webapi module"
depends = ["package:src:webapi:audit:*"]
run = "true"

["package:src:webapi:libyear:libyear-toml"]
hide = true
run = "libyear toml src/webapi/pyproject.toml"

["package:src:webapi:libyear"]
description = "Check src/webapi libyear"
depends = ["package:src:webapi:libyear:*"]
run = "true"
