"""Search domain.

Revision ID: 3ce25ef103a3
Revises: cc2bee6de197
Create Date: 2026-05-31 15:12:01.331440

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

revision = "3ce25ef103a3"
down_revision = "cc2bee6de197"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE search_domain (
            ref_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            version INTEGER NOT NULL,
            archived BOOLEAN NOT NULL,
            created_time TIMESTAMP WITH TIME ZONE NOT NULL,
            last_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
            archived_time TIMESTAMP WITH TIME ZONE,
            workspace_ref_id INTEGER NOT NULL,
            archival_reason VARCHAR,
            PRIMARY KEY (ref_id),
            FOREIGN KEY (workspace_ref_id) REFERENCES workspace (ref_id)
        )
    """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX ix_search_domain_workspace_ref_id
            ON search_domain (workspace_ref_id)
    """
    )

    conn = op.get_bind()
    conn.execute(
        text(
            """
            INSERT INTO search_domain (
                version,
                archived,
                archival_reason,
                created_time,
                last_modified_time,
                archived_time,
                workspace_ref_id
            )
            SELECT
                version,
                archived,
                archival_reason,
                created_time,
                last_modified_time,
                archived_time,
                ref_id
            FROM workspace
            """
        )
    )

    op.add_column(
        "search_entity_indexing_map",
        sa.Column("search_domain_ref_id", sa.Integer(), nullable=True),
    )

    conn.execute(
        text(
            """
            UPDATE search_entity_indexing_map
            SET search_domain_ref_id = (
                SELECT search_domain.ref_id
                FROM search_domain
                WHERE search_domain.workspace_ref_id
                    = search_entity_indexing_map.workspace_ref_id
            )
            """
        )
    )

    op.execute(
        """
        DROP INDEX ix_search_entity_indexing_map_workspace_entity_type
    """
    )
    op.drop_constraint(
        "fk_search_entity_indexing_map_workspace_ref_id",
        "search_entity_indexing_map",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_search_entity_indexing_map_workspace_entity",
        "search_entity_indexing_map",
        type_="unique",
    )
    op.drop_column("search_entity_indexing_map", "workspace_ref_id")
    op.alter_column(
        "search_entity_indexing_map",
        "search_domain_ref_id",
        nullable=False,
    )
    op.create_foreign_key(
        "fk_search_entity_indexing_map_search_domain_ref_id",
        "search_entity_indexing_map",
        "search_domain",
        ["search_domain_ref_id"],
        ["ref_id"],
    )
    op.create_unique_constraint(
        "uq_search_entity_indexing_map_search_domain_entity",
        "search_entity_indexing_map",
        ["search_domain_ref_id", "entity_type", "entity_ref_id"],
    )
    op.execute(
        """
        CREATE INDEX ix_search_entity_indexing_map_search_domain_entity_type
            ON search_entity_indexing_map (search_domain_ref_id, entity_type)
    """
    )

    op.add_column(
        "search_mutation_log",
        sa.Column("search_domain_ref_id", sa.Integer(), nullable=True),
    )

    conn.execute(
        text(
            """
            UPDATE search_mutation_log
            SET search_domain_ref_id = (
                SELECT search_domain.ref_id
                FROM search_domain
                WHERE search_domain.workspace_ref_id
                    = search_mutation_log.workspace_ref_id
            )
            """
        )
    )

    op.drop_constraint(
        "fk_search_mutation_log_workspace_ref_id",
        "search_mutation_log",
        type_="foreignkey",
    )
    op.drop_column("search_mutation_log", "workspace_ref_id")
    op.alter_column(
        "search_mutation_log",
        "search_domain_ref_id",
        nullable=False,
    )
    op.create_foreign_key(
        "fk_search_mutation_log_search_domain_ref_id",
        "search_mutation_log",
        "search_domain",
        ["search_domain_ref_id"],
        ["ref_id"],
    )


def downgrade() -> None:
    conn = op.get_bind()

    op.add_column(
        "search_mutation_log",
        sa.Column("workspace_ref_id", sa.Integer(), nullable=True),
    )
    conn.execute(
        text(
            """
            UPDATE search_mutation_log
            SET workspace_ref_id = (
                SELECT search_domain.workspace_ref_id
                FROM search_domain
                WHERE search_domain.ref_id = search_mutation_log.search_domain_ref_id
            )
            """
        )
    )
    op.drop_constraint(
        "fk_search_mutation_log_search_domain_ref_id",
        "search_mutation_log",
        type_="foreignkey",
    )
    op.drop_column("search_mutation_log", "search_domain_ref_id")
    op.alter_column("search_mutation_log", "workspace_ref_id", nullable=False)
    op.create_foreign_key(
        "fk_search_mutation_log_workspace_ref_id",
        "search_mutation_log",
        "workspace",
        ["workspace_ref_id"],
        ["ref_id"],
    )

    op.execute(
        """
        DROP INDEX ix_search_entity_indexing_map_search_domain_entity_type
    """
    )
    op.add_column(
        "search_entity_indexing_map",
        sa.Column("workspace_ref_id", sa.Integer(), nullable=True),
    )
    conn.execute(
        text(
            """
            UPDATE search_entity_indexing_map
            SET workspace_ref_id = (
                SELECT search_domain.workspace_ref_id
                FROM search_domain
                WHERE search_domain.ref_id
                    = search_entity_indexing_map.search_domain_ref_id
            )
            """
        )
    )
    op.drop_constraint(
        "fk_search_entity_indexing_map_search_domain_ref_id",
        "search_entity_indexing_map",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_search_entity_indexing_map_search_domain_entity",
        "search_entity_indexing_map",
        type_="unique",
    )
    op.drop_column("search_entity_indexing_map", "search_domain_ref_id")
    op.alter_column("search_entity_indexing_map", "workspace_ref_id", nullable=False)
    op.create_foreign_key(
        "fk_search_entity_indexing_map_workspace_ref_id",
        "search_entity_indexing_map",
        "workspace",
        ["workspace_ref_id"],
        ["ref_id"],
    )
    op.create_unique_constraint(
        "uq_search_entity_indexing_map_workspace_entity",
        "search_entity_indexing_map",
        ["workspace_ref_id", "entity_type", "entity_ref_id"],
    )
    op.execute(
        """
        CREATE INDEX ix_search_entity_indexing_map_workspace_entity_type
            ON search_entity_indexing_map (workspace_ref_id, entity_type)
    """
    )

    op.execute("DROP INDEX ix_search_domain_workspace_ref_id")
    op.execute("DROP TABLE search_domain")
