"""time plan questions

Revision ID: a4b2c8d1e059
Revises: 8f3a1c92b047
Create Date: 2026-08-23 17:55:00.000000

"""

from alembic import op

revision = "a4b2c8d1e059"
down_revision = "8f3a1c92b047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE time_plan_domain
            ADD COLUMN order_of_questions JSONB NOT NULL DEFAULT '{}'::jsonb
        """
    )

    op.execute(
        """
        CREATE TABLE time_plan_question (
            ref_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            version INTEGER NOT NULL,
            archived BOOLEAN NOT NULL,
            archival_reason VARCHAR,
            created_time TIMESTAMP WITH TIME ZONE NOT NULL,
            last_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
            archived_time TIMESTAMP WITH TIME ZONE,
            time_plan_domain_ref_id INTEGER NOT NULL,
            name VARCHAR(256) NOT NULL,
            period VARCHAR(32) NOT NULL,
            PRIMARY KEY (ref_id),
            FOREIGN KEY (time_plan_domain_ref_id) REFERENCES time_plan_domain (ref_id)
        )
        """
    )

    op.execute(
        """
        CREATE INDEX ix_time_plan_question_time_plan_domain_ref_id
            ON time_plan_question (time_plan_domain_ref_id)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX ix_time_plan_question_time_plan_domain_ref_id")
    op.execute("DROP TABLE time_plan_question")
    op.execute("ALTER TABLE time_plan_domain DROP COLUMN order_of_questions")
