"""email verification attempt ref id identity

Revision ID: c3cc27543077
Revises: 9b53b5d8b981
Create Date: 2026-06-06 00:18:05.532213

"""

from alembic import op

revision = "c3cc27543077"
down_revision = "9b53b5d8b981"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE email_verification_attempt
        ALTER COLUMN ref_id ADD GENERATED BY DEFAULT AS IDENTITY
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE email_verification_attempt
        ALTER COLUMN ref_id DROP IDENTITY IF EXISTS
        """
    )
