"""'Recovery token sub entity'

Revision ID: ab36fc01bdf0
Revises: 8d7c3e9f2a14
Create Date: 2026-05-17 00:52:24.683709

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "ab36fc01bdf0"
down_revision = "8d7c3e9f2a14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE recovery_token (
            ref_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            version INTEGER NOT NULL,
            archived BOOLEAN NOT NULL,
            archival_reason VARCHAR,
            created_time TIMESTAMP WITH TIME ZONE NOT NULL,
            last_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
            archived_time TIMESTAMP WITH TIME ZONE,
            auth_ref_id INTEGER NOT NULL UNIQUE,
            recovery_token_hash VARCHAR NOT NULL,
            PRIMARY KEY (ref_id),
            FOREIGN KEY (auth_ref_id) REFERENCES auth (ref_id)
        )
    """
    )

    conn = op.get_bind()
    auth_rows = (
        conn.execute(
            text(
                """
            SELECT
                ref_id,
                version,
                archived,
                archival_reason,
                created_time,
                last_modified_time,
                archived_time,
                recovery_token_hash
            FROM auth
            """
            )
        )
        .mappings()
        .all()
    )

    max_ref_id = (
        conn.execute(
            text(
                """
            SELECT MAX(ref_id) AS max_ref_id
            FROM (
                SELECT ref_id FROM auth
                UNION ALL
                SELECT ref_id FROM "user"
                UNION ALL
                SELECT ref_id FROM workspace
                UNION ALL
                SELECT ref_id FROM web_ui_settings
            )
            """
            )
        )
        .mappings()
        .one()["max_ref_id"]
    )
    next_ref_id = (max_ref_id or 0) + 1

    for auth_row in auth_rows:
        conn.execute(
            text(
                """
                INSERT INTO recovery_token (
                    ref_id,
                    version,
                    archived,
                    archival_reason,
                    created_time,
                    last_modified_time,
                    archived_time,
                    auth_ref_id,
                    recovery_token_hash
                )
                OVERRIDING SYSTEM VALUE
                VALUES (
                    :ref_id,
                    :version,
                    :archived,
                    :archival_reason,
                    :created_time,
                    :last_modified_time,
                    :archived_time,
                    :auth_ref_id,
                    :recovery_token_hash
                )
                """
            ),
            {
                "ref_id": next_ref_id,
                "version": auth_row["version"],
                "archived": auth_row["archived"],
                "archival_reason": auth_row["archival_reason"],
                "created_time": auth_row["created_time"],
                "last_modified_time": auth_row["last_modified_time"],
                "archived_time": auth_row["archived_time"],
                "auth_ref_id": auth_row["ref_id"],
                "recovery_token_hash": auth_row["recovery_token_hash"],
            },
        )
        next_ref_id += 1

    if auth_rows:
        conn.execute(
            text(
                """
                SELECT setval(
                    pg_get_serial_sequence('recovery_token', 'ref_id'),
                    (SELECT MAX(ref_id) FROM recovery_token)
                )
                """
            )
        )

    op.drop_column("auth", "recovery_token_hash")


def downgrade() -> None:
    op.add_column(
        "auth",
        sa.Column(
            "recovery_token_hash",
            sa.String(),
            nullable=False,
            server_default="",
        ),
    )

    conn = op.get_bind()
    recovery_rows = (
        conn.execute(
            text(
                """
            SELECT auth_ref_id, recovery_token_hash
            FROM recovery_token
            """
            )
        )
        .mappings()
        .all()
    )

    for recovery_row in recovery_rows:
        conn.execute(
            text(
                """
                UPDATE auth
                SET recovery_token_hash = :recovery_token_hash
                WHERE ref_id = :auth_ref_id
                """
            ),
            {
                "auth_ref_id": recovery_row["auth_ref_id"],
                "recovery_token_hash": recovery_row["recovery_token_hash"],
            },
        )

    op.execute("DROP TABLE recovery_token")
