"""access invite

Revision ID: 59b73a997ea0
Revises: c0031c312aa3
Create Date: 2026-08-08 21:31:29.077000

"""

from alembic import op

revision = "59b73a997ea0"
down_revision = "c0031c312aa3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE access_invite (
            ref_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            version INTEGER NOT NULL,
            archived BOOLEAN NOT NULL,
            archival_reason VARCHAR,
            created_time TIMESTAMP WITH TIME ZONE NOT NULL,
            last_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
            archived_time TIMESTAMP WITH TIME ZONE,
            access_domain_ref_id INTEGER NOT NULL,
            name VARCHAR(255) NOT NULL,
            access_grant_ref_id INTEGER NOT NULL,
            PRIMARY KEY (ref_id),
            FOREIGN KEY (access_domain_ref_id) REFERENCES access_domain (ref_id),
            FOREIGN KEY (access_grant_ref_id) REFERENCES access_grant (ref_id)
        )
    """
    )

    op.execute(
        """
        CREATE INDEX ix_access_invite_access_domain_ref_id
            ON access_invite (access_domain_ref_id)
    """
    )

    op.execute(
        """
        CREATE INDEX ix_access_invite_access_grant_ref_id
            ON access_invite (access_grant_ref_id)
    """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX uq_access_invite_domain_grant
            ON access_invite (access_domain_ref_id, access_grant_ref_id)
    """
    )


def downgrade() -> None:
    op.execute("DROP INDEX uq_access_invite_domain_grant")
    op.execute("DROP INDEX ix_access_invite_access_grant_ref_id")
    op.execute("DROP INDEX ix_access_invite_access_domain_ref_id")
    op.execute("DROP TABLE access_invite")
