"""access request

Revision ID: c0031c312aa3
Revises: 92af836d83d0
Create Date: 2026-08-08 19:43:24.632826

"""

from alembic import op

revision = "c0031c312aa3"
down_revision = "92af836d83d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE access_request (
            ref_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            version INTEGER NOT NULL,
            archived BOOLEAN NOT NULL,
            archival_reason VARCHAR,
            created_time TIMESTAMP WITH TIME ZONE NOT NULL,
            last_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
            archived_time TIMESTAMP WITH TIME ZONE,
            access_domain_ref_id INTEGER NOT NULL,
            name VARCHAR(255) NOT NULL,
            entity VARCHAR NOT NULL,
            principal VARCHAR NOT NULL,
            user_ref_id INTEGER NOT NULL,
            access_level VARCHAR NOT NULL,
            status VARCHAR NOT NULL,
            PRIMARY KEY (ref_id),
            FOREIGN KEY (access_domain_ref_id) REFERENCES access_domain (ref_id)
        )
    """
    )

    op.execute(
        """
        CREATE INDEX ix_access_request_access_domain_ref_id
            ON access_request (access_domain_ref_id)
    """
    )

    op.execute(
        """
        CREATE INDEX ix_access_request_entity
            ON access_request (entity)
    """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX uq_access_request_domain_entity_principal_user
            ON access_request (access_domain_ref_id, entity, principal, user_ref_id)
    """
    )


def downgrade() -> None:
    op.execute("DROP INDEX uq_access_request_domain_entity_principal_user")
    op.execute("DROP INDEX ix_access_request_entity")
    op.execute("DROP INDEX ix_access_request_access_domain_ref_id")
    op.execute("DROP TABLE access_request")
