["docs:prepare"]
hide = true
run  = "true"

["docs:lint:toml"]
hide = true
sources = ["docs/docs.mise.toml"]
outputs = { auto = true }
run = "npx eslint docs/docs.mise.toml"

["docs:lint:mdl-docs"]
hide = true
sources = ["docs/**/*.md"]
outputs = { auto = true }
run = '''
#!/usr/bin/env bash
set -ex
mdl --config="./tasks/_resources/check/lint/mdl-docs" docs/
'''

["docs:lint"]
description = "Check docs module"
depends = ["docs:lint:*"]
run = "true"
