["docs:prepare"]
hide = true
run  = "true"

["docs:fix:markdownlint"]
hide = true
sources = ["docs/**/*.md"]
outputs = { auto = true }
run = "./tasks/_resources/check/lint/markdownlint-cli2.sh --fix 'docs/**/*.md'"

["docs:fix"]
description = "Fix docs module"
depends = ["docs:fix:*"]
run = "true"

["docs:lint:toml"]
hide = true
sources = ["docs/docs.mise.toml"]
outputs = { auto = true }
run = "npx eslint docs/docs.mise.toml"

["docs:lint:markdownlint-docs"]
hide = true
sources = ["docs/**/*.md"]
outputs = { auto = true }
run = "./tasks/_resources/check/lint/markdownlint-cli2.sh 'docs/**/*.md'"

["docs:lint"]
description = "Check docs module"
depends = ["docs:lint:*"]
run = "true"
