"""Retrieve all entity events generated by a particular mutation."""

from jupiter.core.config import (
    JupiterLoggedInReadonlyContext,
    JupiterLoggedInReadonlyUseCase,
)
from jupiter.core.users.root import User
from jupiter.framework.base.entity_id import EntityId
from jupiter.framework.base.mutation_id import MutationId
from jupiter.framework.base.timestamp import Timestamp
from jupiter.framework.use_case import readonly_use_case
from jupiter.framework.use_case_io import (
    UseCaseArgsBase,
    UseCaseResultBase,
    use_case_args,
    use_case_result,
    use_case_result_part,
)


@use_case_args
class GetMutationEntityEventsArgs(UseCaseArgsBase):
    """Arguments for getting entity events from a mutation."""

    mutation_id: MutationId


@use_case_result_part
class EventEntry(UseCaseResultBase):
    """A single entity event produced by a mutation."""

    entity_name: str
    event_kind: str
    event_name: str
    timestamp: Timestamp
    source: str
    user_ref_id: EntityId
    entity_version: int
    data: str


@use_case_result
class GetMutationEntityEventsResult(UseCaseResultBase):
    """Results for the mutation entity events."""

    mutation_name: str
    entries: list[EventEntry]
    users: list[User]


@readonly_use_case()
class GetMutationEntityEventsUseCase(
    JupiterLoggedInReadonlyUseCase[
        GetMutationEntityEventsArgs, GetMutationEntityEventsResult
    ]
):
    """Use case for loading all entity events produced by a mutation."""

    async def _execute(
        self,
        context: JupiterLoggedInReadonlyContext,
        args: GetMutationEntityEventsArgs,
    ) -> GetMutationEntityEventsResult:
        """Execute the command's action."""
        events = await self._invocation_recorder.find_all_entity_events_for_mutation(
            args.mutation_id,
        )

        invocation_records = (
            await self._invocation_recorder.find_all_invocation_records(
                [args.mutation_id],
            )
        )
        mutation_name = invocation_records[0].name if invocation_records else "Unknown"

        events.sort(key=lambda e: e.timestamp, reverse=True)

        async with self._ports.domain_storage_engine.get_unit_of_work() as uow:
            all_users = await uow.get_for(User).find_all(
                allow_archived=True,
                filter_ref_ids=[
                    JupiterLoggedInReadonlyContext.unwrap_str(e.context_str)[0]
                    for e in events
                ],
            )

        return GetMutationEntityEventsResult(
            mutation_name=mutation_name,
            entries=[
                EventEntry(
                    entity_name=e.entity_type,
                    event_kind=e.kind.value,
                    event_name=e.name,
                    timestamp=e.timestamp,
                    source=e.source,
                    user_ref_id=JupiterLoggedInReadonlyContext.unwrap_str(
                        e.context_str
                    )[0],
                    entity_version=e.entity_version,
                    data=e.data,
                )
                for e in events
            ],
            users=all_users,
        )
