---
name: Develop

"on":
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.9.19
          install: true
          cache: true
          experimental: true
      - name: Install dependencies
        run: mise run --jobs=1 install
      - name: Prepare for development
        run: mise run prepare
      - name: Check scripts
        run: mise run check
